ARGoS3-AutoMoDe README
=====================

All useful information about the ARGoS3-AutoMoDe package, including installation and utilization instructions
are regrouped in the following technical report. Please cite this report if you use the ARGoS3-AutoMoDe package.

  CITE here.

Package content
---------------

* bin :: This empty folder will contain the executable automode_main after compilation.
* experiments :: The folder where one should place experiment configuration files (.argos or .xml)
** chocolate :: The experiment configuration files of the experiments described in (cite choco)
** example :: The experiment configuration file used as example in the technical report of the package.
* loop-functions :: The folder where one should place loop functions classes.
** chocolate :: The loop functions files used in the experiments described in (cite choco)
** example :: The loop functions class used as example in the technical report of the package.
* optimization :: The folder where one should place files regarding the optimization algorithm used.
** example :: The necessary elements to launch irace on a small example described in the technical report.
*** execution-folder
*** experiments-folder
*** grammar_generator.sh
*** grammar.txt
*** scenario.txt
*** target-runner
* src :: The source files of ARGoS3-AutoMoDe package.
** cmake ::
** core ::
** modules :: The six behavior and six condition modules described in (cite choco)
** AutoMoDeMain.cpp :: 
